language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
sudo: false
env:
 global:
   - PACKAGE="alcotest"
   - PRE_INSTALL_HOOK="cd /home/opam/opam-repository && git pull origin master && opam update -u -y"
 matrix:
   - DISTRO=debian-stable OCAML_VERSION=4.01.0
   - DISTRO=debian-testing OCAML_VERSION=4.02.3
   - DISTRO=debian-unstable OCAML_VERSION=4.03.0
   - DISTRO=ubuntu-12.04 OCAML_VERSION=4.01.0
   - DISTRO=ubuntu-16.04 OCAML_VERSION=4.03.0
   - DISTRO=centos-6 OCAML_VERSION=4.02.3
   - DISTRO=centos-7 OCAML_VERSION=4.03.0
   - DISTRO=fedora-24 OCAML_VERSION=4.02.3
   - DISTRO=alpine OCAML_VERSION=4.03.0
